### ISSUE TITLE
Missing package: opencv-python-headless 4.0.0.21

### ISSUE THREAD

**Issue by josubg** [bennuttall/piwheels#128]
Missing package
Package name: opencv-python-headless
Link to PyPI page: https://pypi.org/project/opencv-python/
Link to piwheels page: https://www.piwheels.org/simple/opencv-python-headless/
Version:  4.0.0.21

**Comment by bennuttall** [comment]
Building in progress

**Comment by geekinchief** [comment]
So I tried doing an opencv compile as noted here (https://gist.github.com/waveform80/3e6130ccae83012fdcd78c8f082b90ae)  but I got the following error:

Preparing /root/packaging/opencv-v18-contrib0-headless0-neon0
./opencv-python-build: line 59: /root/packaging/opencv-v18-contrib0-headless0-neon0-cmake.log: No such file or directory
!! Skipping ARMv7 build because ARMv6 build failed
Wed 12 Jun 2019 11:36:52 AM HDT
Preparing /root/packaging/opencv-v18-contrib0-headless1-neon0
./opencv-python-build: line 59: /root/packaging/opencv-v18-contrib0-headless1-neon0-cmake.log: No such file or directory
!! Skipping ARMv7 build because ARMv6 build failed
!! Skipping contrib build because non-contrib build failed

**Comment by bennuttall** [comment]
Closing in favour of #172
