### ISSUE TITLE
Consider benefits of adding neon optimisation for ARMv7 wheels

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#30]
A few people have asked if we're using the compiler switches which turn on the neon optimisations, apparently rapidly increasing performance on Pi 2 and 3.

If it's possible, and seems to be worth doing, we would still build without the flags, to provide a Pi 1-compatible wheel, but build again with the flags on, and provide that as the true ARMv7 wheel. I guess we would only rebuild the packages with a not-none ABI tag.

Assuming there's no compatibility issue between Pi 2 and 3, this might be worthwhile. Though it does add further complexity to the system :)

Not a priority, but worth looking into at a later date.

In the mean time, if anyone can provide instructions on building wheels with neon, that would be useful. For example:

```
pip3 wheel numpy
```

outputs a wheel file (after 20 mins) on a Pi 3. If the compiler flags can be added to this command, and produce a faster version, that would be awesome.

**Comment by waveform80** [comment]
Hmmm, on the subject of Pi2 / Pi3 incompatibilities remember that there's two revs of the 2 and one of them has exactly the same CPU as the 3, and one of them doesn't :) Do both have NEON? I can't recall off the top of my head.

**Comment by bennuttall** [comment]
Yeah, neon is available on 2836 and 2837, so original (2836) Pi 2, new (2837) Pi 2 and (2837) Pi 3.

*(when I say "Pi 2" from now on I'm referring to 2836, and "Pi 3" 2837)*

Apparently neon differs between Pi 2 and Pi 3, but Pi 3 is compatible with Pi 2 neon. So because we can't provide different wheels for Pi 2 and Pi 3, we would have to compile Pi 2 neon on Pi 3, and provide that for both (because we can't differentiate when somebody runs `pip install`). Pi 3 users wouldn't get the full benefits of the Pi 3 neon, but Pi 2 neon would give a significant boost over non-neon wheels.

However, if we really wanted to provide different wheels for Pi 2 and Pi 3, we could do that by creating a separate repo branch, say at `piwheels.hostedpi.com/pi3`, and users who specifically want the Pi 3 neon wheels could explicitly choose to use this as their index instead.

This idea also opens up the idea of us providing experimental repo branches for other things like this :)

**Comment by waveform80** [comment]
Quick update on this, with regard to the recent OpenCV uploads:

* The ARMv6 builds were done without NEON (obviously)
* The ARMv7 builds were done with "full fat" Pi3 NEON rather than (older) Pi2

My reasons for changing my mind on supporting "universal" NEON are as follows:

* The audience for 2836 compatible NEON is effectively static at this point (2836-based Pi2s are no longer produced, I think?).
* The audience for 2837-based Pis (new Pi2, Pi3, Pi3+) is continually growing.
* Thus, the audience that cares about NEON *compatible with the 2836* are those who have an old Pi2, want higher performance but for whatever reason cannot or will not obtain a 2837 based Pi2, or Pi3/3+. 
* Choosing to build "universal" NEON wheels would thus be reducing performance for the majority to provide support for a static (in fact, dwindling as a percentage) portion of the community.

**Comment by Dawars** [comment]
What is the status of this and what does the Pi4 mean in this regard?

**Comment by bennuttall** [comment]
opencv and tensorflow wheels are built with neon turned on, the rest are not. Do you see a benefit from this approach with any other packages?

**Comment by Dawars** [comment]
I'm thinking about `numpy` though it might have nothing to do with neon.

I created a separate issue to address it: https://github.com/bennuttall/piwheels/issues/182

**Comment by bennuttall** [comment]
Thanks
