### ISSUE TITLE
Missing package: lxml

### ISSUE THREAD

**Issue by mishas** [bennuttall/piwheels#32]
Hey,

It seems like, for some reason, the lxml package is missing. The folder of the package exists, but it's empty: https://www.piwheels.hostedpi.com/simple/lxml/

looking at the `deploy_slave_{jessie,stretch}.sh` files, you have apt dependencies on `python{,3}-lxml` as well as `python{,3}-yaml`, `python{,3}-pil` and a few more, which would make you think will bring all the required dependencies in order to build those packages, but in reality, they bring the non-dev packages, thus building might fail.

Thank you again for a wonderful project :)

**Comment by bennuttall** [comment]
Thanks for reporting this. We don't have _all_ packages, because some fail to build. We log build output so we can investigate why and fix things (where possible). We hope to soon implement HTML package pages and an API so that users can look up build output and see why some packages failed.

I did a first run of piwheels with nothing installed (just using Raspbian Lite), and I got a 76% success rate. Then we analysed the failures and worked out key missing dependencies. We installed those and ran it again and we got it up to about 87%. Now when anyone finds missing packages, we ask them to report it here (like you have) so that we can try to get a successful build added.

The reason there is an empty page at /simple/lxml is that we automatically create directories for all known packages, and initially create an empty HTML page, which we can then later populate with links to files. We do this because a bug in pip means a 404 in an additional index breaks pip commands, whereas an empty directory passes on to PyPI as expected.

Looking at the build output for `lxml`, the key issue seems to be given here:

```
** make sure the development packages of libxml2 and libxslt are installed **
```

If you can test this and respond here we would appreciate that. Perhaps try installing the dependencies we have in the deploy script on Raspbian Lite, and the additional ones mentioned above, and see if `pip3 wheel lxml --no-deps` produces a wheel.

If you have a list of other missing packages, please post them here if directly related to `lxml`, or in another issue if unrelated. Thanks!

**Comment by mishas** [comment]
I've tested what you suggested, and it seems like the missing package is indeed `libxslt-dev` (you already have `libxml2-dev` in your deploy script).

**Comment by waveform80** [comment]
This should now build over the next few hours - do feel free to re-open if you find anything wrong with the package (or if it  doesn't show up in the next couple of hours or so).

**Comment by bennuttall** [comment]
Yup - it's there!
