### ISSUE TITLE
numpy package doesn't work in conda environment

### ISSUE THREAD

**Issue by RobertLucian** [bennuttall/piwheels#40]
There is an issue with the `numpy` package while it's being imported in python, in a conda environment. 
I have described the issue on conda's repository, so there's no need in repeating myself: https://github.com/conda/conda/issues/6423

What I've noticed is that after I build the wheel from PyPi, the error described on the aforementioned issue disappears. I'm running all this on a Jessie Lite + Raspberry Pi 3.

It might help, so here's the wheel I've built which works on my machine:

[numpy-1.13.3-cp34-cp34m-linux_armv7l.zip](https://github.com/bennuttall/piwheels/files/1543897/numpy-1.13.3-cp34-cp34m-linux_armv7l.zip)

**Comment by waveform80** [comment]
Hmm, after a bit of googling I *think* the root cause is [fpe vs non-fpe builds](https://www.python.org/dev/peps/pep-0513/#fpectl-builds-vs-no-fpectl-builds) of CPython (for reference I found this via h2oai/h2o4gpu#201). In other words, my guess would be that the system build of CPython on Raspbian is compiled with fpectl, but the conda build of CPython isn't?

I'm afraid I can't offer much hope of a fix on the piwheels side; it would imply switching all the build slaves to a non-system CPython build and re-building much of the repo (with little guarantee the result would be as compatible with the system CPython install which is our primary target)

About the best I can offer for now is that setting up your own (potentially private) piwheels installation isn't *that* hard (the code's all open and I hope [the documentation](http://piwheels.readthedocs.io/en/latest/)'s enough to get someone up and running if they're so inclined).

**Comment by RobertLucian** [comment]
Thank you giving your time on this issue.

For the last couple of days, I've been trying to find a way of getting a `fpe-build` of CPython in a conda environment while preserving the capability of updating the supposed conda package with conda. Unfortunately, I didn't get anywhere with it.

I also understand that it would take a fair amount months to switch the build slaves to a `non-fpe build` of CPython and that's quite inconvenient. By the way, it seems like 
> extensions that are built against a no-fpectl CPython are always compatible with yes-fpectl CPython, but the reverse is not necessarily true.

In theory, this could help you switch the build slaves to a `non-fpe` CPython while still having the builds compatible with the system CPython that comes on Rasbian. I haven't deep dived into this, so I cannot be sure this will work for every package - testing would be required before going with it.

As for your advice on how to handle this situation, I think setting up my own builder (based on piwheels) is the best thing I can think of for now. Or at the very least, I can build the wheels for the packages I need manually. To give you a perspective, I need 20-30 python packages installed on (a) offline machine(s) and in the next 6-12 months I can expect bringing in another 20-30 packages to the current environment(s) - so there aren't loads of packages to consider. 

Do you have any other suggestions on how to deal with this?

**Comment by waveform80** [comment]
I think setting up your own custom piwheels installation is probably the best way to go. As for handling just the 20-30 packages you want, that's fairly simple:

1. Set up the database as described [in the docs](http://piwheels.readthedocs.io/en/latest/overview.html)

2. Tweak the packages table so the default for the "skip" column is True:

   ```
   $ sudo su - postgres
   $ psql piwheels
   piwheels=> ALTER TABLE piwheels ALTER COLUMN skip SET DEFAULT true;
   ```

   By way of explanation, the two "top level" tables in piwheels are "packages" (a list of all the packages known about on PyPI with a "skip" setting) and "versions" (a list of all versions of all packages known about on PyPI, again with a "skip" setting).

3. Start up the master with the `--verbose` flag. After a minute or two you'll start seeing *lots* of messages from the cloud_gazer sub-task as it scrapes PyPI for all the registered packages and versions, inserting them into the aforementioned tables. That's fine because it'll be adding them all with skip set to "true" in packages, so nothing will sent out to build.

4. Once cloud_gazer reaches the end of PyPI's event log things will settle down (this'll take several hours). At this point, you can tweak the database to "unskip" the packages you're actually interested in. There's no need to shut the master down for this, so grab another terminal and do something like the following:

   ```
   $ sudo su - postgres
   $ psql piwheels
   piwheels=> SELECT * FROM packages WHERE package = 'numpy';
    package  | skip
   ----------+------
    numpy    | t
   (1 row)

   piwheels=> UPDATE packages SET skip = false WHERE package = 'numpy';
   ```
5. Or, if you only want to "unskip" a single version of a given package:

   ```
   piwheels=> SELECT * FROM versions WHERE package = 'numpy';
    package |   version    | skip
   ---------+--------------+------
    numpy   | 1.8.2        | f
    numpy   | 1.12.0b1     | f
    numpy   | 1.13.0rc1    | f
    numpy   | 1.8.1        | f
    numpy   | 1.11.1       | f
    numpy   | 1.11.2       | f
    numpy   | 1.12.1rc1    | f
    numpy   | 1.9.0        | f
    numpy   | 1.12.0rc2    | f
    numpy   | 1.9.3        | f
    numpy   | 1.11.1rc1    | f
    numpy   | 1.7.2        | f
    numpy   | 1.13.1       | f
    numpy   | 1.13.0       | f
    numpy   | 1.11.0b3     | f
    numpy   | 1.4.1        | f
    numpy   | 1.11.3       | f
    numpy   | 1.7.1        | f
    numpy   | 1.6.2        | f
    numpy   | 1.5.1        | f
    numpy   | 1.10.1       | f
    numpy   | 1.11.0rc2    | f
    numpy   | 1.5.0        | f
    numpy   | 1.9.2        | f
    numpy   | 1.10.2       | f
    numpy   | 1.7.0        | f
    numpy   | 1.13.0rc2    | f
    numpy   | 1.6.1        | f
    numpy   | 1.11.0rc1    | f
    numpy   | 1.8.0        | f
    numpy   | 1.12.0       | f
    numpy   | 1.9.1        | f
    numpy   | 1.6.0        | f
    numpy   | 1.12.0rc1    | f
    numpy   | 1.11.0       | f
    numpy   | 1.10.4       | f
    numpy   | 1.3.0        | f
    numpy   | 1.11.2rc1    | f
    numpy   | 1.10.0       | f
    numpy   | 1.12.1       | f
    numpy   | 1.4.0        | f
    numpy   | 1.5.0b2      | f
    numpy   | 1.10.0.post2 | f
    numpy   | 1.10.3       | f
    numpy   | 1.13.2       | f
    numpy   | 1.13.3       | f
   (46 rows)
   
   piwheels=> UPDATE versions SET skip = true WHERE package = 'numpy' AND version <> '1.13.3';
   piwheels=> UPDATE packages SET skip = false WHERE package = 'numpy';
   ```

   Note: here all the *versions* were already "unskipped" so we set all but the version we want to skip, then "unskipped" the package itself (piwheels avoids building either versions of any package set to skip, or any specific version set to skip). Also note that any *new* versions of the will automatically build (because the package is now "unskipped" and the default for "skip" on the versions table is still false).

6. Everything else should be as normal in the docs. Incidentally you can run the master without any build slaves, so feel free to do that if you just want to get a feel for the database and how the master fills it.

This way you should be able to easily limit the system to just those packages you want to build (sorry there's no "friendlier" interface than SQL; my day-job used to be database administrator so I'm generally happy setting stuff just by bashing SQL in on the command line!).

**Comment by waveform80** [comment]
Oh, damn - just realized I still haven't registered piwheels itself on PyPI. For now you'll have to make do with the following instead of "pip install piwheels":

```
# git clone https://github.com/bennuttall/piwheels.git
# cd piwheels
# python3 setup.py install
```

Sorry! I will get around to the PyPI registration once I've finished a couple more bits!

**Comment by RobertLucian** [comment]
@waveform80 I have been super busy with all the things I had on my plate and sorry for being "late to my own party". First of all, I want to thank you for your support on setting up my own custom piwheels builder - you put in a lot of effort for it. 

Second of all, I resorted to having the packages manually pre-compiled, mainly because I update them quite rarely and because there are only a handful of them. Setting up a custom builder would have been the ideal scenario, but giving the fact that this doesn't take too much time on my hands to do it manually, I can say it's a low hanging fruit. 

With that being said, this still looks a great idea to implement. I think setting up a custom builder will be necessary in the near future when the need to have more up-to-date packages will be more important in my given situation (and when the number of packages will increase). For this matter, I'll hold onto this idea. 

Thank you!
