### ISSUE TITLE
Removing a pypi release doesn't remove the wheel from piwheels

### ISSUE THREAD

**Issue by martinohanlon** [bennuttall/piwheels#45]
This morning, through an error on my own behalf, I realised a project to pip... guizero 0.4.2  Immediately noticing my mistake I removed the release from pypi. Unfortunately the release is now on piwheels, so when people install they get 0.4.2 not 0.4.1!

**Comment by martinohanlon** [comment]
Interestingly I just tried this again and now piwheels has installed 0.4.1... Could this be a timing issue? i.e. Piwheels was still 'catching up'.

**Comment by waveform80** [comment]
You're correct that, at the moment, piwheels doesn't honour removal notices from PyPI largely because it's not been necessary so far. In the general case, when something is removed the typical fix is to release something with a higher version number so it's guaranteed to supersede the withdrawn version in case anyone downloaded it already. But if there's nothing new to release I can easily remove the 0.4.2 build if you'd like?

I can't explain why you're getting 0.4.1 though: 0.4.2 is definitely on piwheels (https://www.piwheels.hostedpi.com/simple/guizero/) and in the builds table:

```
piwheels=# select * from builds where package = 'guizero';
 build_id | package | version | built_by |          built_at          |    duration     | status | abi_tag 
----------+---------+---------+----------+----------------------------+-----------------+--------+---------
  1391649 | guizero | 0.4.0   |        1 | 2017-12-19 17:41:30.642119 | 00:00:05.294699 | t      | cp34m
  1393836 | guizero | 0.4.1   |        3 | 2018-01-03 12:45:09.802892 | 00:00:04.390621 | t      | cp34m
  1412511 | guizero | 0.4.2   |        1 | 2018-01-10 06:33:55.51829  | 00:00:04.992887 | t      | cp34m
   300630 | guizero | 0.1.0   |       11 | 2017-08-07 17:59:30.117599 | 00:00:00.611857 | t      | cp34m
   300631 | guizero | 0.1.1   |        5 | 2017-08-07 17:59:30.234197 | 00:00:00.696795 | t      | cp34m
   300632 | guizero | 0.1.2   |        1 | 2017-08-07 17:59:30.3871   | 00:00:00.787489 | t      | cp34m
   300633 | guizero | 0.2.0   |        5 | 2017-08-07 17:59:31.307622 | 00:00:00.771171 | t      | cp34m
   300634 | guizero | 0.2.1   |        1 | 2017-08-07 17:59:31.505085 | 00:00:00.731533 | t      | cp34m
   300635 | guizero | 0.1.3   |       11 | 2017-08-07 17:59:31.550575 | 00:00:00.7927   | t      | cp34m
   300636 | guizero | 0.3.2   |        1 | 2017-08-07 17:59:32.30104  | 00:00:00.655743 | t      | cp34m
   300637 | guizero | 0.3.0   |        5 | 2017-08-07 17:59:32.438874 | 00:00:00.782133 | t      | cp34m
   300638 | guizero | 0.3.3   |       11 | 2017-08-07 17:59:32.473442 | 00:00:00.776734 | t      | cp34m
(12 rows)
```

**Comment by martinohanlon** [comment]
Could it be that Im getting 0.4.1 because its picking up the wheel from pypi?

**Comment by martinohanlon** [comment]
Ill push the version 0.4.3 - lets keep it clean. Dont worry about deleting.

**Comment by waveform80** [comment]
> Could it be that Im getting 0.4.1 because its picking up the wheel from pypi?

It could well be. I'm not au fait with pip's logic for "extra" indexes, but it's something we'll probably need to dive into at some point to understand these things. Taking a wild guess based on the above, it's possible that when piwheels is listed as an "extra" index (as in Raspbian's current default), it isn't consulted for candidate versions but only for alternate formats of package versions derived from the primary index(es) (PyPI).

It wouldn't surprise me if there were some caching around PyPI so that, when you first registered 0.4.2, it appeared on PyPI, and piwheels built it a minute or less later. Subsequently when it was removed, the cache kept on serving it from PyPI for a short while after deletion. Hence your attempt to install initially picked up 0.4.2 because it was available from PyPI and piwheels, but the later attempt (after the cache expired) didn't pick up 0.4.2 because it wasn't available on PyPI despite there being a wheel for it on piwheels.

All this is speculation on my part but it would explain the pattern of events. Anyway glad it all seems to be sorted!

**Comment by bennuttall** [comment]
@waveform80 is action on this required, or can we close it?

**Comment by waveform80** [comment]
We can close it; I don't anticipate that we *should* honour removal notices from PyPI (the general procedure of releasing something with a higher version is by far the safest move in such a circumstance) and now we've got #39 (a means for easily removing packages) implemented that should be it. However, it might be worth adding a FAQ entry for people wanting packages removed if there isn't one already?

**Comment by bennuttall** [comment]
:+1:

**Comment by bennuttall** [comment]
I've just been asked to delete a package where the author accidentally published version 3.0 instead of 3.0.0 which they removed from pypi but Pi users were still getting 3.0.

I deleted the 3.0 version from the versions table and it cascaded down to builds and files, but I also had to delete the file from master, and manually edit the index file to remove it from the index. I'm sure in time the index would have been updated but I assume only once a new version is released?

It would be nice to honour deletions, or at least provide a simple way for us to delete (like a command line command).

Having said that, is there anything I could have done to streamline the process?

**Comment by waveform80** [comment]
Sure, use piw-remove ;)

**Comment by bennuttall** [comment]
Reopening as action required on docs: https://github.com/bennuttall/piwheels/issues/45#issuecomment-368042814

**Comment by bennuttall** [comment]
`piw-remove` sounds handy. Is that new?
