### ISSUE TITLE
scipy 1.0.1 missing

### ISSUE THREAD

**Issue by bfabio** [bennuttall/piwheels#67]
scipy 1.0.1 is missing from [the repository](https://www.piwheels.hostedpi.com/simple/scipy/) even though `pip3 wheel scipy` manages to compile it on a Raspberry Pi 3.

It needs `libblas-dev` and `liblapack-dev` as build dependencies, but it looks like they are already installed: https://github.com/bennuttall/piwheels/blob/master/deploy_slave.sh#L20.

**Comment by bennuttall** [comment]
This is probably a repeat of #46. Some package maintainers upload their wheels first, then later add sdist, which means piwheels will see there's a new version, try to build it but finds no matching distribution to build from, and fails. We intend to add some logic in to catch situations like these, but until then it requires a manual deletion of the build record, so that it reenters the build queue. I can see it building now so assuming that works it'll appear very shortly (first Python 3.4, later 3.5).

**Comment by bennuttall** [comment]
Wow I forgot scipy takes over an hour to build. It's complete for Python 3.4, and will be queued for 3.5 shortly.

https://www.piwheels.org/simple/scipy/

**Comment by bennuttall** [comment]
Done :+1:
