### ISSUE TITLE
Piwheels breaks amazon-dash installations

### ISSUE THREAD

**Issue by Nekmo** [bennuttall/piwheels#83]
Hello, I'm the amazon-dash project developer and I'm having many issue for piwheels project. I have specific dependencies for Python2 using markers and Pipwheels removes these dependencies. This is causing many issues.

https://github.com/Nekmo/amazon-dash/issues/72
https://github.com/Nekmo/amazon-dash/issues/49
https://github.com/Nekmo/amazon-dash/issues/47
https://github.com/Nekmo/amazon-dash/issues/54
https://github.com/Nekmo/amazon-dash/issues/57
https://github.com/Nekmo/amazon-dash/issues/63
... and more

I have created a wheel on my machine and it works without depencency issues:

```
Metadata-Version: 2.0
Name: amazon-dash
Version: 1.1.1
Summary: Package description
Requires-Dist: PyYAML (>=3.0)
Requires-Dist: jsonschema
Requires-Dist: requests
Requires-Dist: click
Requires-Dist: click-default-group
Requires-Dist: scapy; python_version < "3.0"
Requires-Dist: subprocess32; python_version < "3.0"
Requires-Dist: scapy (>=2.4.0); python_version > "3.0"
```

But the dependencies are broken in Piwheels
```
Metadata-Version: 2.1
Name: amazon-dash
Version: 1.1.1
Summary: Package description
Requires-Dist: PyYAML (>=3.0)
Requires-Dist: jsonschema
Requires-Dist: requests
Requires-Dist: click
Requires-Dist: click-default-group
Requires-Dist: scapy (>=2.4.0)
```

Please tell me how to solve this problem.

Thank you.

**Comment by waveform80** [comment]
Hmm, that's an interesting setup.py. Anyway, after digging into this it appears the reason is that the builders on piwheels are using an up-to-date pip (v18) but setuptools is positively ancient (5.something - whatever's in jessie's apt repos). Sufficiently ancient that, while it understands markers like "python_version > 3.0" in a requirements file, instead of passing them through when building a universal wheel it instead acts upon them, stripping out dependencies that don't match. Hence, because the wheels are being built by a python version > 3.0 all the dependencies marked "python_version < 3.0" (like subprocess32, a back-port of 3.2's subprocess module for 2.7) get stripped from the resulting wheel.

@bennuttall: couple of ways to deal with this. Either mark amazon-dash "skip" so we don't build it in future (not much impact to users; it's a pure python package so the speed-up is negligible anyway) or upgrade setuptools on the builders. To be honest I'd recommend doing that anyway - pip and setuptools are two peas in a pod and it's best to keep them updated together. That said you need to be quite careful when upgrading setuptools; I'd recommend staying away from "pip's install --upgrade" initially as it's liable to trash the apt-installed version. Only use --upgrade once you're sure the version in use is a /usr/local based one.

**Comment by waveform80** [comment]
Oh, it's not even setuptools fault - I just noticed the other branch in "read_requirements_files" in amazon-dash's setup.py:

```python
def read_requirements_files(files):
    reqs = []
    for file in files:
        if StrictVersion(setuptool_version) >= StrictVersion('20.2'):
            reqs.extend([('{};{}'.format(req, file['marker']) if file.get('marker') else req)
                         for req in read_requirements_file(file['name'])])
        elif file.get('include', True):
            # Retrocompatibility mode for setuptools < 20.2
            reqs.extend(list(read_requirements_file(file['name'])))
return reqs
```

Because setuptools is indeed <20.2 on the piwheels builders, that function is stripping out the deps itself. Frankly, it'd probably be better to just blow up with an error there and demand the user upgrade their setuptools rather than produce a supposedly valid universal wheel which isn't really universal, but I presume the intent is to ensure a straight install still works on down-level setuptools (because that'll be the majority use-case anyway).

@bennuttall Despite the above, I'd still recommend upgrading setuptools on the builders - might even be worth re-running the builds since pip was upgraded on them (I forget when you did that - a week or so ago?)

**Comment by bennuttall** [comment]
Ok, setuptools upgraded on all builders - let's add that to the deploy script and see about keeping pip and setuptools up-to-date. Are we going to skip this package or do we think it'll build ok now? I'll kick off another build and we'll see.

**Comment by Nekmo** [comment]
Thanks for your quick answer :)

**Comment by waveform80** [comment]
Worth a re-build I'd say - check the .dist-info/METADATA in the wheel afterward and you should see things like python_version < "3.0" in some of the Requires-Dist headers (if you do, it's built correctly).

**Comment by bennuttall** [comment]
All versions have now been rebuilt - so if you can verify it installs correctly we can close this.

https://www.piwheels.org/simple/amazon-dash/

**Comment by Nekmo** [comment]
```
[nekmo@homura ~]$ mktmpenv -p /usr/bin/python2
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/python2
Also creating executable in /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/preactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/postactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4aff7717dbdd9f9/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-4aff7717dbdd9f9) [nekmo@homura ~/.virtualenvs/tmp-4aff7717dbdd9f9]$ pip install -i https://www.piwheels.org/simple --extra-index-url https://pypi.org/simple amazon-dash
Looking in indexes: https://www.piwheels.org/simple, https://pypi.org/simple
Collecting amazon-dash
  Using cached https://www.piwheels.org/simple/amazon-dash/amazon_dash-1.1.1-py2.py3-none-any.whl
Collecting click-default-group (from amazon-dash)
Collecting PyYAML>=3.0 (from amazon-dash)
Collecting click (from amazon-dash)
  Downloading https://www.piwheels.org/simple/click/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 837kB/s 
Collecting scapy; python_version < "3.0" (from amazon-dash)
Collecting jsonschema (from amazon-dash)
  Downloading https://www.piwheels.org/simple/jsonschema/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting subprocess32; python_version < "3.0" (from amazon-dash)
Collecting requests (from amazon-dash)
  Downloading https://www.piwheels.org/simple/requests/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 2.1MB/s 
Collecting functools32; python_version == "2.7" (from jsonschema->amazon-dash)
Collecting chardet<3.1.0,>=3.0.2 (from requests->amazon-dash)
  Downloading https://www.piwheels.org/simple/chardet/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.4MB/s 
Collecting urllib3<1.24,>=1.21.1 (from requests->amazon-dash)
  Downloading https://www.piwheels.org/simple/urllib3/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 7.9MB/s 
Collecting certifi>=2017.4.17 (from requests->amazon-dash)
  Downloading https://www.piwheels.org/simple/certifi/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 7.1MB/s 
Collecting idna<2.8,>=2.5 (from requests->amazon-dash)
  Downloading https://www.piwheels.org/simple/idna/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 8.7MB/s 
Installing collected packages: click, click-default-group, PyYAML, scapy, functools32, jsonschema, subprocess32, chardet, urllib3, certifi, idna, requests, amazon-dash
Successfully installed PyYAML-3.13 amazon-dash-1.1.1 certifi-2018.4.16 chardet-3.0.4 click-6.7 click-default-group-1.2 functools32-3.2.3.post2 idna-2.7 jsonschema-2.6.0 requests-2.19.1 scapy-2.4.0 subprocess32-3.5.2 urllib3-1.23
```

It works, thank you! :+1:
