### ISSUE TITLE
Broken packages: aiortc and pylibsrtp

### ISSUE THREAD

**Issue by jlaine** [bennuttall/piwheels#89]
Broken package
Package name: `aiortc`
Link to PyPI page: https://pypi.org/project/aiortc
Link to piwheels page: https://www.piwheels.org/simple/aiortc
Version: `all`
More information:

I received a github issue stating that `aiortc` did not install correctly on Raspbian:

https://github.com/jlaine/aiortc/issues/62

I fired up a qemu VM with raspbian/stretch to investigate and discovered that the following wheel was being picked up by pip3:

https://www.piwheels.org/simple/aiortc/aiortc-0.9.6-py3-none-any.whl

This wheel looks wrong:

- it should not be ABI/platform independent
- it should contain two binary extensions should be built for the opus + vpx codecs.

Is there something wrong with the package's setup.py or is this a piwheels issue?

**Comment by bennuttall** [comment]
It seems that something about the dependencies installed on piwheels builders (see the deploy script) makes them build this platform independent wheel.

I've managed to successfully install `airtc` on a Pi by installing only the dependencies that it needs. For now I have deleted the `any` wheels, but I'm in the process of building the wheels offline and will import them into the piwheels system as soon as they're done.

**Comment by bennuttall** [comment]
The new builds have been imported: https://www.piwheels.org/simple/aiortc/

**Comment by bennuttall** [comment]
Note that I have told piwheels to skip this package so unless we resolve this issue, no new versions will be built (unless I see a new release and build it myself). If you want to let me know of any future releases, I'd be happy to, but that's manual and not ideal for either of us.

**Comment by waveform80** [comment]
Oooh - this was a tricky one. It's actually a fault in aiortc's setup.py, but a rather subtle one! The aiortc [setup.py](https://github.com/jlaine/aiortc/blob/master/setup.py) is nice and simple (just what I like!) with one area of mild complexity: it uses CFFI. More specifically, it uses CFFI's setuptools integration to define what needs building. So, it simply lists a few extra arguments to the setuptools.setup call:

```python
setuptools.setup(
    ...,
    cffi_modules=cffi_modules,
    packages=['aiortc', 'aiortc.codecs', 'aiortc.contrib'],
    setup_requires=['cffi'],
    install_requires=['aioice>=0.6.7,<0.7.0', 'attrs', 'av', 'crcmod', 'cryptography>=2.2', 'opencv-python', 'pyee', 'pylibsrtp>=0.5.6', 'pyopenssl'],
)
```

Now, `cffi_modules` isn't normally a valid parameter for the setup() call. What happens to invalid parameters? They're ignored in case an extension wants to deal with them. In this case, the cffi extension (specified in the `setup_requires` parameter) should be loaded and will know what to do with them (due to the aforementioned CFFI setuptools integration).

However, let's compare the above to what CFFI specify in their own docs:

```python
# setup.py (with automatic dependency tracking)
from setuptools import setup

setup(
    ...,
    setup_requires=["cffi>=1.0.0"],
    cffi_modules=["package/foo_build.py:ffibuilder"],
    install_requires=["cffi>=1.0.0"],
)
```

Spot the difference? The `setup_requires` line only specifies "cffi" instead of "cffi>=1.0.0". This may seem minor but it's actually the root of the issue (it's also missing from `install_requires` but that's less important right now). Here's a breakdown of what's going on:

* CFFI's setuptools integration was only added in 1.0.0, so in versions prior to this the `cffi_modules` argument won't be recognized and will simply be ignored.
* The version of CFFI included with Raspbian Jessie is the ancient 0.8.6.
* So here's what happens when we try and run setup.py on the Jessie builders (which are always tried first): setuptools checks that `setup_requires` is satisfied. It is because the cffi module is installed and aiortc hasn't asked for a specific version.
* The `cffi_modules` argument is ignored because neither setuptools nor CFFI know about it.
* As a result it builds a straight pure-Python wheel because aside from the `cffi_modules` everything (that it knows about) is straight-forward pure Python.
* At this point piwheels stops processing any further and doesn't try building it on Raspbian Stretch (which has CFFI 1.9.1) because as far as we know we've successfully built a pure-Python wheel that'll work on either version.

Incidentally, building on Raspbian Stretch fails: CFFI tries to compile its modules but we're missing a load of video codec header deps. Still, that's what *should* be happening on Raspbian Jessie too.

So, steps to correct this:

1. aiortc need to fix their setup.py to include "cffi>=1.0.0" in both `setup_requires` and `install_requires`.
2. We need to wipe the pure Python wheels (I think Ben's already done that).
3. Unmark the package for skip and mark all *current* versions for skip because we want to (attempt to) build future versions once the setup.py is fixed.

Once the setup.py is fixed, future Raspbian Jessie builds will still fail (because they'll have an ancient CFFI install and the builders aren't allowed to install their own deps during build). However, we should then fall through to try on Raspbian Stretch. That'll also fail at the moment (because of the missing deps) but then if there's demand for it we can just install those deps and set it to rebuild. In either case at least we won't be serving broken pure-Python wheels for this package.

**Comment by jlaine** [comment]
Wow, thank you very much for the detailed feedback! I had not realized the versioned dependency on cffi would have so much impact, I might submit a PR for cffi's documentation to highlight the consequences of not versioning the dependency.

I will go and fix aiortc's setup.py as well as pylibsrtp's as it suffers from the same problem.

**Comment by bennuttall** [comment]
Wow thanks @waveform80.

Are the wheels I built ok? I built them on Raspbian Stretcn Desktop, not a cloud Pi. Does that mean it had the deps it needed? Will it build on Jessie too, or not?

**Comment by jlaine** [comment]
I have fixed aiortc's setup.py based on the feedback provided by @waveform80 and pushed out aiortc 0.9.7.

I have unfortunately discovered that pylibsrtp had the same issue so we have some py3-none-any.whl wheels on piwheels, which need to be cleared out:

https://www.piwheels.org/simple/pylibsrtp/

Would it be possible to add libsrtp2-dev to the deploy script and trigger a rebuild of pylibsrtp (0.6.0) and then aiortc (0.9.7) ?

**Comment by bennuttall** [comment]
Done!

```
piwheels=> select * from versions where package = 'aiortc';
 package | version | skip
---------+---------+------
 aiortc  | 0.9.7   | f
 aiortc  | 0.9.3   | t
 aiortc  | 0.9.2   | t
 aiortc  | 0.9.1   | t
 aiortc  | 0.9.0   | t
 aiortc  | 0.8.0   | t
 aiortc  | 0.7.0   | t
 aiortc  | 0.6.0   | t
 aiortc  | 0.5.0   | t
 aiortc  | 0.4.0   | t
 aiortc  | 0.4.1   | t
 aiortc  | 0.3.0   | t
 aiortc  | 0.2.0   | t
 aiortc  | 0.1.0   | t
 aiortc  | 0.9.4   | t
 aiortc  | 0.9.5   | t
 aiortc  | 0.9.6   | t
```

```
piwheels=> select * from versions where package = 'pylibsrtp';                      
  package  | version | skip
-----------+---------+------
 pylibsrtp | 0.6.0   | f
 pylibsrtp | 0.5.5   | t
 pylibsrtp | 0.5.4   | t
 pylibsrtp | 0.5.3   | t
 pylibsrtp | 0.5.2   | t
 pylibsrtp | 0.5.1   | t
 pylibsrtp | 0.5.0   | t
 pylibsrtp | 0.4.1   | t
 pylibsrtp | 0.4.2   | t
 pylibsrtp | 0.4.0   | t
 pylibsrtp | 0.3.0   | t
 pylibsrtp | 0.2.0   | t
 pylibsrtp | 0.1.0   | t
 pylibsrtp | 0.5.6   | t
 pylibsrtp | 0.5.7   | t
```

```
piwheels=> select version, abi_tag, built_by from builds where package = 'aiortc';  
 version | abi_tag | built_by
---------+---------+----------
 0.4.1   | cp35m   |        0
 0.5.0   | cp35m   |        0
 0.6.0   | cp35m   |        0
 0.7.0   | cp35m   |        0
 0.8.0   | cp35m   |        0
 0.9.0   | cp35m   |        0
 0.9.1   | cp35m   |        0
 0.9.2   | cp35m   |        0
 0.9.3   | cp35m   |        0
 0.9.4   | cp35m   |        0
 0.9.5   | cp35m   |        0
 0.9.6   | cp35m   |        0
 0.9.7   | cp35m   |        6
 0.9.7   | cp34m   |        2
```

`0` denotes imported from offline build. `6` is a stretch builder, `2` is a jessie builder (hence `cp34m` tag).

Do my imported wheels actually work? If so will they build on jessie too? If so I'll build and import them as well.

Will we be able to also build older versions of `pylibsrtp` offline?

https://www.piwheels.org/simple/aiortc
https://www.piwheels.org/simple/pylibsrtp

**Comment by jlaine** [comment]
Thanks! I'd say forget about older pylibsrtp releases, their bindings were too specific to very recent libsrtp versions to be useful and I have pulled them off pypi.

Once aiortc 0.9.7 is built I'll give it a spin and report back.

**Comment by jlaine** [comment]
I forgot to answer one of your questions: aiortc should be able to build on Jessie, but it won't be much use as pylibsrtp (which it depends on) cannot.

**Comment by jlaine** [comment]
aiortc 0.9.7 doesn't seem to have been built, is there a build log somewhere?

**Comment by bennuttall** [comment]
Sorry my mistake, missing deps. I'll install and rebuild.

**Comment by bennuttall** [comment]
Installed `libopus-dev` and `libvpx-dev`, rebuilding 0.9.7 now.

**Comment by jlaine** [comment]
Beautiful, thanks so much @bennuttall and @waveform80, the wheels work fine!

Looking forward to seeing what creative uses the Pi community finds for WebRTC :)

**Comment by bennuttall** [comment]
:+1:
